module.exports = {
  GET_TRACKS: "GET_TRACKS",
  GET_TRACK: "GET_TRACK",
  PUBLIC_AUDIO_URL_RECEIVED: "PUBLIC_AUDIO_URL_RECEIVED",
  PUBLIC_IMAGE_URL_RECEIVED: "PUBLIC_IMAGE_URL_RECEIVED",
  PRESIGNED_URL_RECEIEVED: "PRESIGNED_URL_RECEIEVED",
  CLEAR_UPLOAD_STORE: "CLEAR_UPLOAD_STORE",
  PLAY_TRACK: "PLAY_TRACK",
  PAUSE_TRACK: "PAUSE_TRACK"
};
