module.exports = {
  GET_TRACKS: "GET_TRACKS",
  GET_TRACK: "GET_TRACK",
  PUBLIC_URL_RECEIVED: "PUBLIC_URL_RECEIVED",
  PRESIGNED_URL_RECEIEVED: "PRESIGNED_URL_RECEIEVED",
  CLEAR_UPLOAD_STORE: "CLEAR_UPLOAD_STORE"
};
