module.exports = {
  LOGIN_USER: "LOGIN_USER",
  ERROR_RECEIVED: "RECEIVE_ERROR",
  LOGOUT_USER: "LOGOUT_USER",
  DESTROY_USER: "DESTROY_USER",
  CREATE_USER: "CREATE_USER",
  LOGGEDIN_RESPONSE: "LOGGEDIN_RESPONSE"
};
